"""`make gen`: ontology YAML -> gen/ (DDL, Pydantic models, JSON schemas, ontology index)."""
from __future__ import annotations

import json
import shutil
from pathlib import Path

from codegen.loader import ROOT, Ontology, load_ontology
from codegen.meta import Attribute

GEN = ROOT / "gen"
BANNER = "GENERATED by `make gen` from ontology/*.yaml — do not edit."
LAYER_NAMES = {
    1: "Value chain", 2: "Functional processes", 3: "Product and asset",
    4: "Ecosystem and channel", 5: "Performance and risk", 6: "Consumer and experience",
}


def columns(onto: Ontology, attrs: dict[str, Attribute]) -> list[tuple[str, str]]:
    """(column, DDL type) pairs; decimals get an exact-text companion column."""
    out = []
    for name, a in attrs.items():
        out.append((name, onto.common.type_map[a.type]))
        if a.type == "decimal":
            out.append((f"{name}_text", "STRING"))
    return out


# ---------------------------------------------------------------- DDL
def gen_ddl(onto: Ontology) -> str:
    lines = [f"// {BANNER}", f"// ontology hash: {onto.hash}", ""]
    for cls in sorted(onto.classes):
        cols = ", ".join(f"{c} {t}" for c, t in columns(onto, onto.node_attributes(cls)))
        lines.append(f"CREATE NODE TABLE {cls}({cols}, PRIMARY KEY(id));")
    lines.append("")
    for rel in sorted(onto.relationships):
        d = onto.relationships[rel]
        pairs = ", ".join(f"FROM {p.from_} TO {p.to}" for p in d.pairs)
        cols = ", ".join(f"{c} {t}" for c, t in columns(onto, onto.edge_properties(rel)))
        lines.append(f"CREATE REL TABLE {rel}({pairs}, {cols});")
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------- Pydantic
PY_TYPES = {
    "string": "str", "int64": "int", "double": "float", "decimal": "float", "bool": "bool",
    "date": "datetime.date", "timestamp": "datetime.datetime", "string_list": "list[str]",
}


def _py_type(a: Attribute) -> str:
    if a.type == "enum":
        return "Literal[" + ", ".join(repr(v) for v in a.values or []) + "]"
    return PY_TYPES[a.type]


def _fields(attrs: dict[str, Attribute], force_optional: bool = False) -> list[str]:
    out = []
    for name, a in attrs.items():
        t = _py_type(a)
        if a.required and not force_optional:
            out.append(f"    {name}: {t}")
        else:
            out.append(f"    {name}: {t} | None = None")
        if a.type == "decimal":
            out.append(f"    {name}_text: str | None = None  # amount exactly as stated")
    return out


def gen_models(onto: Ontology) -> str:
    out = [
        f'"""{BANNER}"""',
        "from __future__ import annotations",
        "",
        "import datetime",
        "from typing import Literal",
        "",
        "from pydantic import BaseModel, ConfigDict, model_validator",
        "",
        f'ONTOLOGY_HASH = "{onto.hash}"',
        "",
        "",
        "class NodeBase(BaseModel):",
        '    model_config = ConfigDict(extra="forbid")',
        *_fields(onto.common.node_base),
        "",
    ]
    for cls in sorted(onto.classes):
        c = onto.classes[cls]
        out += ["", f"class {cls}(NodeBase):", f'    """{c.description.strip()} (layer {c.layer})"""']
        out += _fields(c.attributes) or ["    pass"]
        out.append("")

    out += ["", "NODE_MODELS: dict[str, type[NodeBase]] = {"]
    out += [f'    "{cls}": {cls},' for cls in sorted(onto.classes)]
    out += ["}", "", "ALLOWED_PAIRS: dict[str, set[tuple[str, str]]] = {"]
    for rel in sorted(onto.relationships):
        pairs = ", ".join(f'("{p.from_}", "{p.to}")' for p in onto.relationships[rel].pairs)
        out.append(f'    "{rel}": {{{pairs}}},')
    out += ["}", ""]

    rel_props: dict[str, Attribute] = {}
    for d in onto.relationships.values():
        rel_props.update(d.properties)
    rel_names = ", ".join(repr(r) for r in sorted(onto.relationships))
    out += [
        "",
        "class Edge(BaseModel):",
        '    """One relationship instance; properties outside the relationship\'s declaration must be None."""',
        '    model_config = ConfigDict(extra="forbid")',
        f"    relationship: Literal[{rel_names}]",
        "    from_type: str",
        "    from_id: str",
        "    to_type: str",
        "    to_id: str",
        *_fields(onto.common.edge_base),
        *_fields(rel_props, force_optional=True),
        "",
        '    @model_validator(mode="after")',
        "    def _allowed_pair(self) -> \"Edge\":",
        "        if (self.from_type, self.to_type) not in ALLOWED_PAIRS[self.relationship]:",
        "            raise ValueError(",
        '                f"{self.relationship} not allowed from {self.from_type} to {self.to_type}"',
        "            )",
        "        own = EDGE_PROPERTIES[self.relationship]",
        "        stray = [p for p in REL_PROPERTY_NAMES if p not in own and getattr(self, p) is not None]",
        "        if stray:",
        '            raise ValueError(f"{self.relationship} does not declare properties {stray}")',
        "        missing = [p for p in EDGE_REQUIRED[self.relationship] if getattr(self, p) is None]",
        "        if missing:",
        '            raise ValueError(f"{self.relationship} missing required properties {missing}")',
        "        return self",
        "",
        "",
        f"REL_PROPERTY_NAMES = {sorted(rel_props)!r}",
        "EDGE_PROPERTIES: dict[str, set[str]] = {",
    ]
    for rel in sorted(onto.relationships):
        out.append(f'    "{rel}": {set(onto.relationships[rel].properties) or "set()"},')
    out += ["}", "EDGE_REQUIRED: dict[str, list[str]] = {"]
    for rel in sorted(onto.relationships):
        req = [p for p, a in onto.relationships[rel].properties.items() if a.required]
        out.append(f'    "{rel}": {req!r},')
    out += ["}", ""]
    return "\n".join(out)


# ---------------------------------------------------------------- JSON schema
def gen_extraction_schema(onto: Ontology) -> dict:
    """Finance spec §7 envelope, constrained to declared classes and relationships."""
    source = {
        "type": "object",
        "required": ["source_system", "source_record_id", "source_reference", "extraction_confidence"],
        "properties": {
            "source_system": {"type": "string"},
            "source_record_id": {"type": "string"},
            "source_reference": {"type": "string"},
            "extraction_confidence": {"type": "number", "minimum": 0, "maximum": 1},
        },
        "additionalProperties": False,
    }
    classes = sorted(onto.classes)
    rels = sorted(onto.relationships)
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$comment": BANNER,
        "title": "ExtractionOutput",
        "type": "object",
        "required": ["entities", "relationships", "unresolved_items"],
        "additionalProperties": False,
        "properties": {
            "entities": {"type": "array", "items": {
                "type": "object",
                "required": ["entity_type", "entity_id", "name", "source"],
                "additionalProperties": False,
                "properties": {
                    "entity_type": {"enum": classes},
                    "entity_id": {"type": "string"},
                    "name": {"type": "string"},
                    "source_label": {"type": "string"},
                    "description": {"type": "string"},
                    "attributes": {"type": "object"},
                    "source": source,
                },
            }},
            "relationships": {"type": "array", "items": {
                "type": "object",
                "required": ["subject_type", "subject_id", "relationship", "object_type", "object_id", "source"],
                "additionalProperties": False,
                "properties": {
                    "subject_type": {"enum": classes},
                    "subject_id": {"type": "string"},
                    "relationship": {"enum": rels},
                    "object_type": {"enum": classes},
                    "object_id": {"type": "string"},
                    "attributes": {"type": "object"},
                    "source": source,
                },
            }},
            "unresolved_items": {"type": "array", "items": {
                "type": "object",
                "required": ["source_text", "reason"],
                "additionalProperties": False,
                "properties": {
                    "source_text": {"type": "string"},
                    "reason": {"type": "string"},
                    "candidate_entity_types": {"type": "array", "items": {"enum": classes}},
                    "candidate_relationships": {"type": "array", "items": {"enum": rels}},
                },
            }},
            "validation_results": {"type": "object"},
        },
        "x-allowed-pairs": {
            r: [[p.from_, p.to] for p in onto.relationships[r].pairs] for r in rels
        },
    }


def gen_slice_schema(onto: Ontology, name: str) -> dict:
    """LLM-facing schema for one slice (DECISIONS D40).

    Kept to the JSON-Schema subset structured-output APIs accept: no additionalProperties, no
    free-form objects. Attributes are [{key, value}] pairs, coerced to ontology types after
    extraction. Provenance is added by the pipeline from the chunk, not produced by the model.
    """
    sl = onto.slices.slices[name]
    kv = {"type": "array", "items": {"type": "object", "required": ["key", "value"],
                                     "properties": {"key": {"type": "string"}, "value": {"type": "string"}}}}
    conf = {"type": "number", "minimum": 0, "maximum": 1}
    return {
        "type": "object",
        "required": ["entities", "relationships", "unresolved_items"],
        "properties": {
            "entities": {"type": "array", "items": {
                "type": "object",
                "required": ["entity_type", "entity_id", "name", "source_label", "attributes", "confidence"],
                "properties": {
                    "entity_type": {"type": "string", "enum": sl.classes},
                    "entity_id": {"type": "string"},
                    "name": {"type": "string"},
                    "source_label": {"type": "string"},
                    "attributes": kv,
                    "confidence": conf,
                },
            }},
            "relationships": {"type": "array", "items": {
                "type": "object",
                "required": ["subject_type", "subject_id", "relationship", "object_type", "object_id", "confidence"],
                "properties": {
                    "subject_type": {"type": "string", "enum": sl.classes},
                    "subject_id": {"type": "string"},
                    "relationship": {"type": "string", "enum": sl.relationships},
                    "object_type": {"type": "string", "enum": sl.classes},
                    "object_id": {"type": "string"},
                    "confidence": conf,
                },
            }},
            "unresolved_items": {"type": "array", "items": {
                "type": "object",
                "required": ["source_text", "reason"],
                "properties": {
                    "source_text": {"type": "string"},
                    "reason": {"type": "string"},
                    "candidate_entity_types": {"type": "array", "items": {"type": "string"}},
                },
            }},
        },
    }


def gen_index(onto: Ontology) -> dict:
    return {
        "_comment": BANNER,
        "hash": onto.hash,
        "layers": LAYER_NAMES,
        "modules": onto.modules,
        "classes": {
            n: {
                "layer": c.layer, "module": c.module, "description": c.description.strip(),
                "stub": c.stub, "source_key": c.source_key, "spec_ref": c.spec_ref,
                "attributes": {k: a.model_dump(exclude_none=True) for k, a in c.attributes.items()},
            }
            for n, c in sorted(onto.classes.items())
        },
        "node_base": {k: a.model_dump(exclude_none=True) for k, a in onto.common.node_base.items()},
        "relationships": {
            n: {
                "description": d.description.strip(), "hook_layer": d.hook_layer, "modules": d.modules,
                "pairs": [p.model_dump(by_alias=True, exclude_none=True) for p in d.pairs],
                "properties": {k: a.model_dump(exclude_none=True) for k, a in d.properties.items()},
            }
            for n, d in sorted(onto.relationships.items())
        },
    }


def run() -> Ontology:
    onto = load_ontology()
    if GEN.exists():
        shutil.rmtree(GEN)
    (GEN / "ddl").mkdir(parents=True)
    (GEN / "json_schema").mkdir()
    (GEN / "__init__.py").write_text(f'"""{BANNER}"""\n', encoding="utf-8")
    (GEN / "ddl" / "schema.cypher").write_text(gen_ddl(onto), encoding="utf-8")
    (GEN / "models.py").write_text(gen_models(onto), encoding="utf-8")

    import importlib
    import gen.models as models  # noqa: E402 — freshly written

    importlib.reload(models)
    for cls, model in models.NODE_MODELS.items():
        schema = model.model_json_schema()
        schema["$comment"] = BANNER
        _dump(GEN / "json_schema" / f"{cls}.json", schema)
    _dump(GEN / "json_schema" / "extraction_output.json", gen_extraction_schema(onto))
    if onto.slices:
        (GEN / "json_schema" / "slices").mkdir()
        for name in onto.slices.slices:
            _dump(GEN / "json_schema" / "slices" / f"{name}.json", gen_slice_schema(onto, name))
    _dump(GEN / "ontology_index.json", gen_index(onto))
    (GEN / ".ontology_hash").write_text(onto.hash, encoding="utf-8")
    print(f"gen: {len(onto.classes)} node tables, {len(onto.relationships)} rel tables, "
          f"{len(onto.pair_set())} FROM-TO pairs (hash {onto.hash})")
    return onto


def _dump(path: Path, obj: dict) -> None:
    path.write_text(json.dumps(obj, indent=2, default=str) + "\n", encoding="utf-8")
